-- 3-1
SELECT TABLE_SCHEMA, TABLE_NAME, PARTITION_NAME, PARTITION_ORDINAL_POSITION,
TABLE_ROWS
FROM INFORMATION_SCHEMA.PARTITIONS
WHERE TABLE_NAME = 'parttbl';

-- 3-2
SELECT * FROM partTBL WHERE birthYear < 1970;

-- 3-3
EXPLAIN SELECT * FROM partTBL WHERE birthYear < 1970;

-- 3-4
EXPLAIN SELECT * FROM partTBL WHERE birthYear <= 1970;
