/*
 * 1
 * BOOK 테이블에서 가격 10,000 이상, 2021년 출판 도서들
 * BOOK_ID, CATEGORY, PRICE 선택
 */

SELECT BOOK_ID, CATEGORY, PRICE FROM BOOK_TABLE
WHERE PRICE >= 10000 AND PUBLISHED_DATE LIKE '2021-%';

/**
 * 2
 * BOOK 테이블에서 '생활' 카테고리 혹은 AUTHOR_ID 1번인 도서
 * BOOK_ID, CATEGORY, AUTHOR_ID 선택
 * (BOOK_ID를 기준 오름차순)
 */

SELECT BOOK_ID, CATEGORY, AUTHOR_ID FROM BOOK_TABLE
WHERE CATEGORY='생활' OR AUTHOR_ID=1
ORDER BY BOOK_ID ASC;

/**
 * 3
 * BOOK 테이블에서 작가별 출간 도서 수
 * AUTHOR_ID, BOOK_COUNT 선택
 * (도서 수 기준 내림차순 -> 작가 ID 기준 오름차순)
 */

SELECT AUTHOR_ID, COUNT(*) AS BOOK_COUNT FROM BOOK_TABLE
GROUP BY AUTHOR_ID
ORDER BY BOOK_COUNT DESC, AUTHOR_ID ASC;

/**
 * 4
 * 평균 일일 대여료 20,000원 이상인 차종 선택
 * (평균 대여료가 높은 순)
 */

SELECT CAR_TYPE, AVG(DAILY_FEE) AS AVG_DAILY_FEE FROM CAR_TABLE
GROUP BY CAR_TYPE
HAVING AVG_DAILY_FEE >= 20000
ORDER BY AVG_DAILY_FEE DESC;

/**
 * 5
 * 각 차종별 대여된 총 횟수 선택
 */

SELECT CAR_TYPE AS 차종, COUNT(*) AS "대여 횟수" FROM (
  SELECT CAR_TABLE.CAR_TYPE AS CAR_TYPE FROM CAR_TABLE
  INNER JOIN CAR_HISTORY_TABLE ON CAR_HISTORY_TABLE.CAR_ID = CAR_TABLE.CAR_ID
) AS QUERIED GROUP BY CAR_TYPE
ORDER BY "대여 횟수" DESC;

/**
 * 6
 * 2022년 10월 3일에 대여 시작된 자동차들의 차종, 일일 대여료, 대여 시작일 조회
 */

SELECT CAR_TABLE.CAR_TYPE AS 차종, CAR_TABLE.DAILY_FEE AS "일일 대여료",
       CAR_HISTORY_TABLE.START_DATE AS "대여 시작일"
FROM CAR_TABLE
INNER JOIN CAR_HISTORY_TABLE ON CAR_HISTORY_TABLE.CAR_ID = CAR_TABLE.CAR_ID
WHERE CAR_HISTORY_TABLE.START_DATE = '2022-10-03';
