#ifndef _CONFIG

#define _CONFIG

#define DEBUG 1
#define DEBUG_SERIAL_SPEED 9600
#define DEBUG_MSG_DEBUG_IS_ON "Debug Mode Enabled"

#define PIN_POTM A0
#define PIN_LED 3
#define ADDR_LCD_A 0x27
#define ADDR_LCD_B 20
#define ADDR_LCD_C 4

#define LCD_DEFAULT_PRINT_LN1 "INIT..."
#define LCD_DEFAULT_PRINT_LN2 "PLEASE WAIT"

#define LCD_PRINT_LN1_X 0
#define LCD_PRINT_LN1_Y 0
#define LCD_PRINT_LN2_X 0
#define LCD_PRINT_LN2_Y 1

#define LCD_PRINT_SET_VALUE_POINT_X 5
#define LCD_PRINT_SET_VALUE_POINT_Y 0
#define LCD_PRINT_LED_VALUE_POINT_X 5
#define LCD_PRINT_LED_VALUE_POINT_Y 1

#define LCD_PRINT_STATUS_LN1 "SET: "
#define LCD_PRINT_STATUS_LN2 "LED: "

#define VALUE_SET_LBOUND 0
#define VALUE_SET_HBOUND 1023
#define VALUE_LED_LBOUND 0
#define VALUE_LED_HBOUND 255

#define LED_REFRESH_INTERVAL 100
#define LED_REFRESH_POSTPROC_RENEW_VALUE 0
#define LED_HUMD_ON 255
#define LED_HUMD_OFF 0

#define STARTUP_LED LED_HUMD_OFF
#define STARTUP_LCD_REFRESH_FLAG 100
#endif
