package io.github.shapelayer.models;

public enum Party {
  DEMOCRATIC_PARTY_OF_KOREA,
  UNITED_FUTURE_PARTY,
  MINSAENGDANG,
  JUSTICE_PARTY,
  OUR_REPUBLICAN_PARTY,
  THE_PEOPLES_PARTY_OF_SOUTH_KOREA,
  KOREAN_ECONOMIC_PARTY,
  THE_PEOPLES_PARTY,
  PRO_PARK_NEW_PARTY,
  OPEN_DEMOCRATIC_PARTY,
}
