[tool.poetry]
name = "directory-labeler"
version = "0.1.0"
description = ""
authors = ["Park, Jonghyeon <belline0124@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
