-- 4-1
ALTER TABLE partTBL
REORGANIZE PARTITION part3 INTO (
  PARTITION part3 VALUES LESS THAN (1974),
  PARTITION part4 VALUES LESS THAN MAXVALUE
);
OPTIMIZE TABLE partTBL;

-- 4-2
SELECT TABLE_SCHEMA, TABLE_NAME, PARTITION_NAME, PARTITION_ORDINAL_POSITION, TABLE_ROWS
FROM INFORMATION_SCHEMA.PARTITIONS
WHERE TABLE_NAME = 'parttbl';

-- 4-3
ALTER TABLE partTBL
  REORGANIZE PARTITION part1, part2 INTO (
PARTITION part12 VALUES LESS THAN (1972)
);
OPTIMIZE TABLE partTBL;

-- 4-4
SELECT TABLE_SCHEMA, TABLE_NAME, PARTITION_NAME, PARTITION_ORDINAL_POSITION, TABLE_ROWS
FROM INFORMATION_SCHEMA.PARTITIONS
WHERE TABLE_NAME = 'parttbl';

-- 4-5
ALTER TABLE partTBL DROP PARTITION part12;
OPTIMIZE TABLE partTBL;

-- 4-6
SELECT * FROM partTBL;
