-- 2-1
CREATE DATABASE IF NOT EXISTS partDB;
USE partDB;
DROP TABLE IF EXISTS partTBL;

CREATE TABLE partTBL (
  userID CHAR(8) NOT NULL,
  userName VARCHAR(10) NOT NULL,
  birthYear INT NOT NULL,
  addr CHAR(2) NOT NULL
)
PARTITION BY RANGE(birthYear) (
  PARTITION part1 VALUES LESS THAN (1970),
  PARTITION part2 VALUES LESS THAN (1972),
  PARTITION part3 VALUES LESS THAN MAXVALUE
);

-- 2-2
INSERT INTO partTBL
SELECT userID, userName, birthYear, addr FROM cookDB.userTBL;

-- 2-3
SELECT * FROM partTBL;
