[Interface]
Address = 172.16.0.##__IDENTIFIER__##/24
PrivateKey = ##__SELF_PRIVATE_KEY__##

[Peer]
PublicKey = ##__HOST_PUBLIC_KEY__##
Endpoint = 192.168.1.161:55500
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
